Refactor registration activity to UI/ViewModel/Model layers
BrugApp/brug pull request #110
Opened 2022-03-21 07:33 UTC by pmcintyr

refactor the registerUser class into UI/ViewModel/Model as seen in the App's architecture in issue https://github.com/BrugApp/brug/issues/98.

2022-03-21 21:29 UTC, DeepGreen1 submitted a review, later dismissed
Good work for the refactoring!
I let you some comments to read; l can approve the request if we agree to do them with the next refactor (the one due to the new "database" class), as we are all depending on the architecture changes before implementing the actual weekly work.

2022-03-21 21:29 UTC, DeepGreen1 commented on app/src/main/java/com/github/brugapp/brug/ui/RegisterUserActivity.kt
> +            FirebaseAuth.getInstance(),
FirebaseAuth.getInstance() is java code, you could update it for kotlin code: Firebase.auth (see here: https://firebase.google.com/docs/auth/android/start#kotlin+ktx_2 )

Also, be careful with the next line (35) that I think, would return the same database (kotlin code this time)

2022-03-21 21:29 UTC, DeepGreen1 commented on app/src/main/java/com/github/brugapp/brug/ui/RegisterUserActivity.kt
> +            .addOnCompleteListener(this) { task ->
To have even better separation of UI/Logic, you could try to split this method. If it's possible, the createAuthAccount() should handle all the logic that is made here: call addRegisterUserTask and print log text where the onClickHelper should only update the progressBar, show the toast and call the method inside the viewmodel.

2022-03-21 21:29 UTC, DeepGreen1 commented on app/src/main/java/com/github/brugapp/brug/view_model/RegisterUserViewModel.kt
> +    private lateinit var progressBar: ProgressBar
To separate view/Logic, the viewmodel should not contain any UI element (progressBar / EditText fields). You can send these values as parameter when you call the method from the activity.

2022-03-21 21:29 UTC, DeepGreen1 commented on app/src/main/java/com/github/brugapp/brug/view_model/RegisterUserViewModel.kt
> +    fun addRegisterUserTask(userToAdd: HashMap<String, Any>): Task<DocumentReference> {
Maybe add a TODO and/or a task in the scrum board to think to update this part of the code when the database class is created. (db will be changed from FirebaseFirestore to our new fancy class :) )

2022-03-21 22:45 UTC, ha2san approved these changes
Really nice work, I have nothing to add to what @DeepGreen1 said. I'm not an expert in app architecture but it seems adequate to me.

2022-03-21 23:21 UTC, pmcintyr commented on app/src/main/java/com/github/brugapp/brug/view_model/RegisterUserViewModel.kt
> +    private lateinit var progressBar: ProgressBar
This causes lots of **code duplication** when passing the same parameters to multiple functions but i did it anyway. If this issue comes up, I will redirect them here.

2022-03-21 23:22 UTC, pmcintyr commented on app/src/main/java/com/github/brugapp/brug/ui/RegisterUserActivity.kt
> +            .addOnCompleteListener(this) { task ->
done

2022-03-21 23:23 UTC, pmcintyr commented on app/src/main/java/com/github/brugapp/brug/ui/RegisterUserActivity.kt
> +            FirebaseAuth.getInstance(),
done in https://github.com/BrugApp/brug/pull/110/commits/d326ba81c162987a9633c1da83820ccc7995397b

2022-03-22 07:58 UTC, omarelmalki requested changes
Great job on the refactoring !
Make sure to preserve the abstraction between each layer. Checkout my suggestions to make sure the activity does not know the rest of the app is using Firebase.

2022-03-22 07:58 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/ui/RegisterUserActivity.kt
> +            Firebase.firestore,
Here, the Activity layer (Activity class + xml file) should not be aware that the viewModel uses Firebase. I suggest keeping Firebase.auth and Firebase.firestore as attributes in the RegisterUserViewModel class so you do not have to put them as argument.
```suggestion
```

2022-03-22 07:58 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/view_model/RegisterUserViewModel.kt
> +    private lateinit var mAuth: FirebaseAuth
```suggestion
    private val db: FirebaseFirestore = Firebase.firestore
    private val mAuth: FirebaseAuth = Firebase.auth
```

2022-03-22 07:58 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/view_model/RegisterUserViewModel.kt
> +        db: FirebaseFirestore,
```suggestion
```

2022-03-22 07:58 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/view_model/RegisterUserViewModel.kt
> +        this.mAuth = mAuth
```suggestion
```

2022-03-22 10:35 UTC, pmcintyr commented on app/src/main/java/com/github/brugapp/brug/ui/RegisterUserActivity.kt
> +            Firebase.firestore,
good idea! thank you for this feedback, i have now implemented it in this commit: https://github.com/BrugApp/brug/pull/110/commits/4188a218e6f70b8aae558fc29f648dce21812b74

2022-03-22 11:21 UTC, merged