Feature/user icon profile
BrugApp/brug pull request #144
Opened 2022-04-02 13:05 UTC by ha2san

Add possibility of setting and changing the profile picture

2022-04-02 15:05 UTC, omarelmalki reviewed
Great work, try to clean up comments if they are not useful. Checkout the comments I left below.

2022-04-02 15:05 UTC, omarelmalki commented on app/src/androidTest/java/com/github/brugapp/brug/SettingsTest.kt
> +//)
It would be great to delete this commented code.

2022-04-02 15:05 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/ui/SettingsActivity.kt
> +    //}
Why is this code commented, the SettingsViewModel is not useful in SignInActivity ?

2022-04-02 16:22 UTC, ha2san commented
> Great work, try to clean up comments if they are not useful. Checkout the comments I left below.

Hi thank you, I had tried several implementations and forgot to remove the old commented codes. Concerning the viewModel, it is now used in the fragment and not in the activity

2022-04-02 16:59 UTC, omarelmalki approved these changes
Good job, thanks for the changes.

2022-04-03 10:08 UTC, hamzahass requested changes
Good work on your task, however consider the comments listed bellow.

2022-04-03 10:08 UTC, hamzahass commented on app/src/main/java/com/github/brugapp/brug/view_model/ChatMenuViewModel.kt
> +                User("Henry", "Crawford", "crawform@services.co.uk", "129271", MockDatabase.currentUser.getProfilePicture() ),
For your tests, and your class in general, how will integrate this with the real Database instead of the Mockdatabase ?

2022-04-03 10:08 UTC, hamzahass commented on app/src/main/res/layout/activity_settings.xml
> +-->
Why is this part commented in your xml ? If not needed you can juste delete it

2022-04-03 10:08 UTC, hamzahass commented on app/src/androidTest/java/com/github/brugapp/brug/SettingsTest.kt
> +        }
For testing it is better to use Hamcrest matchers and assertThat instead of JUnit assert method.

2022-04-03 12:26 UTC, ha2san commented on app/src/main/res/layout/activity_settings.xml
> +-->
Indeed, I forgot to remove this part thanks.

2022-04-03 12:27 UTC, ha2san commented on app/src/androidTest/java/com/github/brugapp/brug/SettingsTest.kt
> +        }
thanks for the advice

2022-04-03 12:29 UTC, ha2san commented on app/src/main/java/com/github/brugapp/brug/view_model/ChatMenuViewModel.kt
> +                User("Henry", "Crawford", "crawform@services.co.uk", "129271", MockDatabase.currentUser.getProfilePicture() ),
We will discuss this in a meeting with the whole group. This part using the mock is for testing purposes only

2022-04-03 12:30 UTC, hamzahass commented on app/src/main/java/com/github/brugapp/brug/view_model/ChatMenuViewModel.kt
> +                User("Henry", "Crawford", "crawform@services.co.uk", "129271", MockDatabase.currentUser.getProfilePicture() ),
Okay thanks

2022-04-03 13:14 UTC, hamzahass approved these changes
Thanks for the changes following the comments

2022-04-03 13:15 UTC, merged