Make Sign In Activity as home to limit guest user abilities
BrugApp/brug pull request #145
Opened 2022-04-02 14:56 UTC by omarelmalki

2022-04-02 16:47 UTC, ha2san approved these changes
Good job, everything looks good to me and seems to work on my end. The tests also look good to me. I think it's a good idea that you left the demo mode for now

2022-04-06 11:31 UTC, Mouniraki requested changes
Good job, your changes may also solve some issues I have with some tests related to the SignIn actions. Consider my comments before approval :)

2022-04-06 11:31 UTC, Mouniraki commented on app/src/main/java/com/github/brugapp/brug/ui/components/CustomTopBar.kt
> +    fun defineTopBarActions(view: View, dummyText: String, item: MenuItem, currentActivity: Activity) {
Does the view attribute still make sense here, since you are passing an Activity as argument ?

2022-04-06 11:31 UTC, Mouniraki commented on app/src/androidTest/java/com/github/brugapp/brug/sign_in/SignInActivityTestFake.kt
> +                        ItemsMenuActivity::class.java.name
As said in previous PRs, try to import the libraries to make your code a bit more compact

2022-04-06 11:34 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/ui/components/CustomTopBar.kt
> +    fun defineTopBarActions(view: View, dummyText: String, item: MenuItem, currentActivity: Activity) {
Good question, I needed an activity as argument and added it and did not want to affect previous functionality as the view wasn't used anyways so I assumed it was probably setup by someone for future use.

2022-04-06 11:34 UTC, omarelmalki commented on app/src/androidTest/java/com/github/brugapp/brug/sign_in/SignInActivityTestFake.kt
> +                        ItemsMenuActivity::class.java.name
Sure, I'll fix that.

2022-04-07 04:32 UTC, omarelmalki commented on app/src/androidTest/java/com/github/brugapp/brug/sign_in/SignInActivityTestFake.kt
> +                        ItemsMenuActivity::class.java.name
Fixed.

2022-04-07 07:06 UTC, Mouniraki approved these changes
Great ! Ready to merge for me !

2022-04-07 07:07 UTC, merged