Add last location to Firebase Items
BrugApp/brug pull request #285
Opened 2022-05-15 12:36 UTC by omarelmalki

Add last location to Firebase items when getting items from or updating items in Firestore.

2022-05-16 09:29 UTC, Mouniraki requested changes
Good job, but consider my comments before getting an approval. It will improve the readability/correctness of the app.

2022-05-16 09:29 UTC, Mouniraki commented on app/src/main/java/com/github/brugapp/brug/data/ItemsRepository.kt
> +                    "last_longitude" to item.getLastLocation()?.getLongitude()
I see that you set the last location by splitting the longitude and latitude in two distinct fields. However, Firebase has the GeoPoint type handling location objects, and we have a LocationService class handling these objects in our app. Consider using it instead of doing what you have done.

2022-05-16 12:52 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/data/ItemsRepository.kt
> +                    "last_longitude" to item.getLastLocation()?.getLongitude()
Good idea, done in last commit.

2022-05-16 17:04 UTC, Mouniraki approved these changes
Great job ! Please see my comments before merging, they can be very useful for improving readability & correctness of your functions I think.

2022-05-16 17:04 UTC, Mouniraki commented on app/src/main/java/com/github/brugapp/brug/data/ItemsRepository.kt
> +                    "last_location" to item.getLastLocation()?.toFirebaseGeoPoint()
Are you sure that setting a GeoPoint object to null in Firebase doesn't produce any errors ? In case there is no last location for the item, isn't it a better idea to simply not include the field in the Firebase document, and check if the field is present in the getter function ?

2022-05-16 20:19 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/data/ItemsRepository.kt
> +                    "last_longitude" to item.getLastLocation()?.getLongitude()
This is an outdated version of the code. This issue was fixed a few commits ago.

2022-05-16 20:21 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/ui/ChatActivity.kt
> +                        conversation.lostItem.setLastLocation(lon, lat)
This could be done indeed by creating a new constructor but for now I am keeping the version with longitude and latitude.

2022-05-16 20:23 UTC, omarelmalki commented on app/src/main/java/com/github/brugapp/brug/data/ItemsRepository.kt
> +                    "last_location" to item.getLastLocation()?.toFirebaseGeoPoint()
This doesn't produce errors, I tried it. I believe it is a better idea to standardise attributes of items by keeping it null when the last location is not available.

2022-05-17 07:25 UTC, hamzahass approved these changes
Thanks for adding the last localisation of objects to Firebase, consider my comments bellow.

2022-05-17 07:25 UTC, hamzahass commented on app/src/androidTest/java/com/github/brugapp/brug/ItemsRepositoryTest.kt
> +        assertThat(list!!.contains(ITEM), IsEqual(true))
Consider putting only one assertion for better maintainability, as it would be better to find the problem if the test fails in the futur

2022-05-17 07:25 UTC, hamzahass commented on app/src/androidTest/java/com/github/brugapp/brug/ItemsRepositoryTest.kt
> +        assertThat(items!!.contains(updatedItem), IsEqual(true))
same here

2022-05-17 15:26 UTC, merged