Notifications implementation
BrugApp/brug pull request #312
Opened 2022-05-19 15:04 UTC by Mouniraki

Addresses issue #335.
This PR involves the following changes :
- Fixed calls to Firebase Messaging in repo classes, now they are properly made and notification messages are sent correctly
- Improved error handling in QrCodeScannerActivity upon scanning QR Code
- Clicking on a notification redirects to ChatMenuActivity, if the user is still signed in (otherwise redirects to SignInActivity)

2022-05-25 07:54 UTC, hamzahass approved these changes
Great work, works well on my end ! Consider the comments I left bellow.

2022-05-25 07:54 UTC, hamzahass commented on app/src/androidTest/java/com/github/brugapp/brug/ItemsMenuActivityTest.kt
>      /** THIS TEST FAILED DUE TO THE PRESSBACK, WEIRD ISSUE RELATED TO RESUMING THE ACTIVITY */
Is the issue related to this comment fixed ?

2022-05-25 07:54 UTC, hamzahass commented on app/src/main/java/com/github/brugapp/brug/view_model/QrCodeScanViewModel.kt
> +                //else "ERROR: Unable to send the messages to the user. Please send him a new message yourself."
When is this case handled ?

2022-05-25 08:35 UTC, Mouniraki commented on app/src/androidTest/java/com/github/brugapp/brug/ItemsMenuActivityTest.kt
>      /** THIS TEST FAILED DUE TO THE PRESSBACK, WEIRD ISSUE RELATED TO RESUMING THE ACTIVITY */
Yes it is resolved now, this comment will be deleted in a future commit.

2022-05-25 08:37 UTC, Mouniraki commented on app/src/main/java/com/github/brugapp/brug/ui/QrCodeScannerActivity.kt
>          //TODO: REMOVE THIS HARDCODED TEXT
I think that it should still be set here for further debuggings before the demo preparations are completely done and every known bug is fixed, so it will be removed in one of the last PRs of the project, but not in this one.

2022-05-25 14:58 UTC, omarelmalki reviewed
I tried running your branch locally but whenever I click on the settings button, the app crashes with `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.brugapp.brug/com.github.brugapp.brug.ui.SettingsActivity}: java.lang.ClassCastException: com.github.brugapp.brug.DaggerBrugApp_HiltComponents_SingletonC$ActivityCImpl cannot be cast to com.github.brugapp.brug.ui.SettingsActivity_GeneratedInjector.`

2022-05-25 23:27 UTC, Mouniraki commented
> I tried running your branch locally but whenever I click on the settings button, the app crashes with `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.brugapp.brug/com.github.brugapp.brug.ui.SettingsActivity}: java.lang.ClassCastException: com.github.brugapp.brug.DaggerBrugApp_HiltComponents_SingletonC$ActivityCImpl cannot be cast to com.github.brugapp.brug.ui.SettingsActivity_GeneratedInjector.` Maybe the app assumes that the user is signed in when he is not. Can you double check if you also have this issue?

HI ! I tried to reproduce the issue on my end, but I wasn't able to do so. Could you maybe elaborate a bit more on what you did/how did you access the app before having the issue ?

2022-05-26 01:09 UTC, omarelmalki requested changes
Hi, the issue with the settings seems to be fixed now.
I can now confirm that the notifications are correctly sent but unfortunately scanning an item does not create a conversation on my end and does not save the location of the object now like it used to do earlier. I tried deleting my conversations without success. Do you have this issue on your end?

2022-05-26 02:43 UTC, omarelmalki reviewed
.

2022-05-26 02:44 UTC, omarelmalki approved these changes
Great job, the feature now works on my end too. Good job !

2022-05-26 17:44 UTC, merged