add Firebase User Registration
BrugApp/brug pull request #76
Opened 2022-03-14 13:40 UTC by pmcintyr

create User/Item collections in Firestore & integrate Firestore registration in project

2022-03-15 15:12 UTC, DeepGreen1 requested changes
Good chunk of work!
Did you try the "optimize the imports" tool in the IDE?

2022-03-15 15:12 UTC, DeepGreen1 commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-auth:19.2.0'
It would be interesting to see if we can use the latest version of the firebase-auth API

2022-03-15 15:12 UTC, DeepGreen1 commented on app/src/main/java/com/github/brugapp/brug/sign_in/SignInResultHandler.kt
> +        println("I am in correct handler")
You should remove those comments

2022-03-15 15:12 UTC, DeepGreen1 commented on app/src/main/java/com/github/brugapp/brug/RegisterUser.kt
> +            firstName?.requestFocus() //return
Are the "return" comments necessary?

2022-03-15 19:38 UTC, omarelmalki reviewed
Nice work !
Feel free to check out the few comments I left.
Also, optionally, since you added and configured Firebase and Firestore, it would be great if you could add a page in the wiki to explain to the developers in the team how to use it.

For further PRs, as a general rule, I would suggest separating concerns by not coding everything in the Activity class. There is a page in the wiki that explains the app architecture we will be using when developing the app, you can already check it out.
But do not worry about it for this PR as there will be an example of how to do it in my next PR and we will adapt the code next sprint.

2022-03-16 08:36 UTC, pmcintyr commented on app/src/main/java/com/github/brugapp/brug/RegisterUser.kt
> +            firstName?.requestFocus() //return
you are right, these comments have now been deleted

2022-03-16 08:36 UTC, pmcintyr commented on app/src/main/java/com/github/brugapp/brug/sign_in/SignInResultHandler.kt
> +        println("I am in correct handler")
you are right, these comments have now been deleted

2022-03-16 08:37 UTC, pmcintyr commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-auth:19.2.0'
yes, as Omar stated in his code review :  since we are using the BoM, we do not need to specify versions in Firebase library dependencies.

2022-03-16 08:38 UTC, pmcintyr commented on app/build.gradle
> +    implementation 'com.google.firebase:firebase-auth:19.2.0'
I agree with you, this has been corrected now!

2022-03-16 08:40 UTC, pmcintyr commented on app/src/main/java/com/github/brugapp/brug/User.kt
> +class User(firstnametxt: String, lastNametxt: String, emailtxt: String, passwordtxt: String) {
I took a closer look, we never used this User class! I was using it for informational purposes only, we do no longer need this so the class has been removed.

2022-03-16 12:12 UTC, DeepGreen1 approved these changes
Good work, thanks for the changes.

2022-03-16 18:41 UTC, omarelmalki approved these changes
Great job, thanks for the changes. Feel free to check out Hilt (see wiki) to mock Firebase authentication to test the rest of your code.

2022-03-16 19:59 UTC, Mouniraki reviewed
Nice job ! Check all my different comments on the code for suggestions, otherwise everything looks good to me

2022-03-16 19:59 UTC, Mouniraki commented on app/src/main/AndroidManifest.xml
> -<?xml version="1.0" encoding="utf-8"?>
I don't really understand what are the real changes here, it seems that the whole file has been changed according to Git but I don't see much real changes

2022-03-16 19:59 UTC, Mouniraki commented on app/src/main/java/com/github/brugapp/brug/RegisterUser.kt
> +    private var progressBar: ProgressBar? = null
Consider using lateinit variables instead of initializing the values to null

2022-03-16 19:59 UTC, Mouniraki commented on app/src/androidTest/java/com/github/brugapp/brug/RegisterUserTest.kt
> +        Espresso.onView(ViewMatchers.withId(R.id.newAccount))
Avoid calling the Espresso functions with the Class names to trim your code a bit, since you already imported them in your test class

2022-03-16 21:24 UTC, pmcintyr commented on app/src/main/AndroidManifest.xml
> -<?xml version="1.0" encoding="utf-8"?>
Sorry about that, I made some modifications that I decided to retract. The file is identical!

2022-03-17 07:34 UTC, pmcintyr commented on app/src/main/java/com/github/brugapp/brug/RegisterUser.kt
> +    private var progressBar: ProgressBar? = null
good point, i have corrected this in the most recent commit

2022-03-17 07:34 UTC, pmcintyr commented on app/src/androidTest/java/com/github/brugapp/brug/RegisterUserTest.kt
> +        Espresso.onView(ViewMatchers.withId(R.id.newAccount))
good idea, i have modified this in the most recent commit

2022-03-17 07:45 UTC, merged