Add UI for Chat Menu Activity
BrugApp/brug pull request #78
Opened 2022-03-15 14:25 UTC by Mouniraki

Implementation of issue #65.

This PR involves the following changes :
- Added new ChatMenuActivity activity, with its UI components in the associated XML file
- Added new chat_entry_layout.xml, specifically for list entries related to ChatMenuActivity
- Removed ItemsViewModel and ItemsCustomAdapter, replaced by more general ListViewModel and ListCustomAdapter classes 
- Moved list callback implementation from ItemsMenuActivity to a new separate ListCustomCallback class to avoid code duplications with the Chat Menu UI implementation
- Moved ViewHolder implementation from the old ItemsCustomAdapter to a new separate ListViewHolder class
- Implemented transitions with Bottom Navigation Bar in ChatMenuActivity and ItemsMenuActivity (i.e., clicking on the different menus trigger a transition to the requested view)

2022-03-15 22:22 UTC, ha2san approved these changes
Really nice work !!! The refactoring makes it easier  for other implementation. I just see a small issue when we click the scan button, since this activity can be started in several ways (from the main activity or from the menu list) we should find a way to return to the right activity when the back button is pressed. It would also be nice to find a way to link an Item with a ListViewModel. Other than that I don't see any problem. It's really a good job!

2022-03-16 19:06 UTC, Mouniraki commented
> Really nice work !!! The refactoring makes it easier for other implementation. I just see a small issue when we click the scan button, since this activity can be started in several ways (from the main activity or from the menu list) we should find a way to return to the right activity when the back button is pressed. It would also be nice to find a way to link an Item with a ListViewModel. Other than that I don't see any problem. It's really a good job!

Thank you ! Indeed, this would be a great thing to do in another sprint, I didn't do it on purpose since it didn't have any link with my task for this week. I will discuss with the scrum master to mark this as a new task to do for next sprint.

2022-03-17 12:23 UTC, omarelmalki requested changes
Great work! 
Please checkout the few comments I left to improve tests.

2022-03-17 12:23 UTC, omarelmalki commented on app/src/androidTest/java/com/github/brugapp/brug/ChatMenuActivityTest.kt
> +
Here I would suggest putting Intents.init() and Intents.release() in @Before and @After  annotated functions. Since you have multiple tests that use intents, it avoids conflicts with init() and release() between tests and code duplication.
```suggestion
@Before
fun setUp() {
    Intents.init()
}

@After
fun finishUp() {
    Intents.release()
}
```

2022-03-17 12:23 UTC, omarelmalki commented on app/src/androidTest/java/com/github/brugapp/brug/ChatMenuActivityTest.kt
> +        Intents.init()
See previous comment. Do the same in all tests.
```suggestion
```

2022-03-17 12:23 UTC, omarelmalki commented on app/src/androidTest/java/com/github/brugapp/brug/ChatMenuActivityTest.kt
> +        Intents.release()
See previous comment. Do the same in all tests.
```suggestion
```

2022-03-17 12:23 UTC, omarelmalki commented on app/src/androidTest/java/com/github/brugapp/brug/ItemsMenuActivityTest.kt
Same comment as for [ChatMenuActivityTest.kt](https://github.com/BrugApp/brug/pull/78/files#diff-32426a0acbd2043338f2f969056704e5c803b46a3ea851c6a6787236ade28bb4)

2022-03-17 13:24 UTC, pmcintyr commented
_Hello! Here are my comments/questions for the code review._
**chatMenuActivityTest**: I was wondering what the advantage of using uiSelector over espresso? can you test more ui-actions with uiSelector?

**settingstest**: you can remove these unused imports:

```
import android.content.Intent
import androidx.test.core.app.ApplicationProvider
import androidx.test.espresso.Espresso
```

**list_item_tint.xml**: we have a warning for an unused item:
`R.color.list_item_tint`
If we do not need it, we can remove it. Unless we are planning on using it later in the project?

2022-03-17 13:31 UTC, Mouniraki commented
> _Hello! Here are my comments/questions for the code review._ **chatMenuActivityTest**: I was wondering what the advantage of using uiSelector over espresso? can you test more ui-actions with uiSelector?
> 
> **settingstest**: you can remove these unused imports:
> 
> ```
> import android.content.Intent
> import androidx.test.core.app.ApplicationProvider
> import androidx.test.espresso.Espresso
> ```
> 
> **list_item_tint.xml**: we have a warning for an unused item: `R.color.list_item_tint` If we do not need it, we can remove it. Unless we are planning on using it later in the project?

Hi ! Thank you for your questions/suggestions, which I am answering one by one below :
- **chatMenuActivityTest** : using UIAutomator enables more elaborate UI testing that isn't possible (or very hard and tedious) to do with Espresso. For instance, the drag-to-reorder feature I added to the lists is very easy to test using UI Automator, but almost impossible to do properly using Espresso. I will suggest using UIAutomator as much as possible for UI testing in the future.
- **settingsTest** : Good point, I didn't really take a look at this test class since it was outside the scope of my task, but I will do the imports optimization before merging everything.
- **list_item_tint.xml** : I forgot to delete the file while refactoring, normally it will be gone in the next commit. Thank you for noticing it :)

2022-03-17 13:34 UTC, Mouniraki commented
> _Hello! Here are my comments/questions for the code review._ **chatMenuActivityTest**: I was wondering what the advantage of using uiSelector over espresso? can you test more ui-actions with uiSelector?
> 
> **settingstest**: you can remove these unused imports:
> 
> ```
> import android.content.Intent
> import androidx.test.core.app.ApplicationProvider
> import androidx.test.espresso.Espresso
> ```
> 
> **list_item_tint.xml**: we have a warning for an unused item: `R.color.list_item_tint` If we do not need it, we can remove it. Unless we are planning on using it later in the project?

Hi ! Thank you for your questions/suggestions, which I am answering one by one below :
- **chatMenuActivityTest** : using UIAutomator enables more elaborate UI testing that isn't possible (or very hard and tedious) to do with Espresso. For instance, the drag-to-reorder feature I added to the lists is very easy to test using UI Automator, but almost impossible to do properly using Espresso. I will suggest using UIAutomator as much as possible for UI testing in the future.
- **settingsTest** : Good point, I didn't really take a look at this test class since it was outside the scope of my task, but I will do the imports optimization before merging everything.
- **list_item_tint.xml** : I forgot to delete the file while refactoring, normally it will be gone in the next commit. Thank you for noticing it :)

2022-03-17 13:37 UTC, Mouniraki commented on app/src/androidTest/java/com/github/brugapp/brug/ChatMenuActivityTest.kt
> +
Thank you for your suggestion, indeed it seems to be a better way to manage the Intents in my tests, and it avoids unnecessary code duplication. This will be fixed in the next commit.

2022-03-17 17:54 UTC, omarelmalki approved these changes
Hi, great job, thanks for the changes !

2022-03-17 18:03 UTC, DeepGreen1 approved these changes
Really nice work!
It would be good to see if we can continue to refactor some classes when the chat activity will be integrated in the app as both code will use an adaptor to map objects to elements of the view (for the recyclerview), but it's future work. Again: well done!

2022-03-17 18:07 UTC, merged